dist: bionic
language: ruby
rvm: 2.6
gemfile:
  - Gemfile
  - test/gemfiles/makara3.gemfile
services:
  - postgresql
addons:
  postgresql: 10
script: bundle exec rake test
before_script:
  - createdb distribute_reads_test_primary
  - createdb distribute_reads_test_replica
matrix:
  include:
    - gemfile: test/gemfiles/activerecord52.gemfile
      env: ADAPTER=mysql2
      services:
        - mysql
      before_script:
        - mysqladmin create distribute_reads_test_primary
        - mysqladmin create distribute_reads_test_replica
notifications:
  email:
    on_success: never
    on_failure: change
