name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.4
            gemfile: Gemfile
          - ruby: 3.3
            gemfile: Gemfile
          - ruby: 3.2
            gemfile: gemfiles/activerecord70.gemfile
          - ruby: 3.1
            gemfile: gemfiles/activerecord61.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: ankane/setup-postgres@v1
      - run: |
          createdb distribute_reads_test_primary
          createdb distribute_reads_test_replica
      - run: bundle exec rake test

      - uses: ankane/setup-mysql@v1
      - run: |
          mysqladmin create distribute_reads_test_primary
          mysqladmin create distribute_reads_test_replica
        # Ruby 3.1 is fixed in 0.6.0.pre
        # Active Record 7.1+ is currently broken
      - if: ${{ matrix.ruby < 3.1 }}
        run: ADAPTER=mysql2 bundle exec rake test
